### ISSUE TITLE
Docker - Licence key argument not working

### ISSUE THREAD

**Issue by syndrael** [hakanensari/country#11]
Hello,
I've tried command: docker run -d -p 3000:3000 hakanensari/country -e LICENSE_KEY=YOUR_LICENSE_KEY
by replacing YOUR_LICENCE_KEY by 3 differents licences
But it does not work.
LICENSE_KEY=XXX
^

ReferenceError: XXX is not defined
    at [eval]:1:1
    at Script.runInThisContext (vm.js:134:12)
    at Object.runInThisContext (vm.js:310:38)
    at internal/process/execution.js:81:19
    at [eval]-wrapper:6:22
    at evalScript (internal/process/execution.js:80:60)
    at internal/main/eval_string.js:27:3

It seems that there's a new licence key generation.
Could you check it ?
Regards

**Comment by hakanensari** [comment]
Thanks for reporting, @syndrael; just fixed
